name: Start actions
on:
  push:
    branches: [ develop ]

jobs:
  analyze-and-test:
    name: Analyze & Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.1  # Use latest stable Flutter version
          channel: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Code
        run: flutter analyze

      - name: Run Tests
        run: flutter test